services:
  app:
    build:
      context: .
    ports:
      - "${PATHWAY_PORT:-8000}:${PATHWAY_PORT:-8000}"
    networks:
      - network
    environment:
      PATHWAY_PORT: "${PATHWAY_PORT:-8000}"
      PATHWAY_LICENSE_KEY: $PATHWAY_LICENSE_KEY
    volumes:
      - ./data:/app/data
      - ./Cache:/app/Cache
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PATHWAY_PORT:-8000}/v2/list_documents" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  ui:
    build:
      context: ui
    networks:
      - network
    environment:
      PATHWAY_HOST: "app"
      PATHWAY_PORT: "${PATHWAY_PORT:-8000}"
      UI_PORT: 8501
    ports:
      - "8501:8501"
    depends_on:
      app:
        condition: service_healthy
networks:
  network:
    driver: bridge
